name: CubelinesShop
version: 1.0
author: dofault
main: main.Main


commands:
  supermarket:
    description: Commande principale du plugin Supermarket
    usage: /supermarket <entry|exit|save|setprice>