name: CubelinesShop
version: 1.0
author: dofault
main: io.dofault.supermarket.main.Main
api-version: '1.21.4'


commands:
  supermarket:
    description: Commande principale du plugin Supermarket
    usage: /supermarket <entry|exit|save|setprice>